server:
  port: 8070

logging:
  level:
    org:
      springframework: INFO

spring:
  application:
    name: SRIMALAR_EXAMPLE_OAUTH
  web:
    resources:
      static-locations: classpath:static
database:
  config: data/config/db.properties

