server:
  port: 8080
spring:
  application:
    name: SRIMALAR_SAMPLE_ACTIVEMQ
  activemq:
    broker-url: tcp://localhost:9876
    mode: native
    pool:
      enabled: true
      max-connections: 50
